# Generated by Django 5.2.17 on 2026-09-27 08:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="ad"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1", max_length=7, verbose_name="renk"
                    ),
                ),
            ],
            options={
                "verbose_name": "etiket",
                "verbose_name_plural": "etiketler",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="güncellenme"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ad")),
                (
                    "domain",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="alan adı"
                    ),
                ),
                (
                    "industry",
                    models.CharField(blank=True, max_length=100, verbose_name="sektör"),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-10", "1-10"),
                            ("11-50", "11-50"),
                            ("51-250", "51-250"),
                            ("251-1000", "251-1000"),
                            ("1000+", "1000+"),
                        ],
                        max_length=10,
                        verbose_name="çalışan sayısı",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="telefon"),
                ),
                ("address", models.TextField(blank=True, verbose_name="adres")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="şehir"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="Türkiye",
                        max_length=100,
                        verbose_name="ülke",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sorumlu",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="companies",
                        to="crm.tag",
                        verbose_name="etiketler",
                    ),
                ),
            ],
            options={
                "verbose_name": "firma",
                "verbose_name_plural": "firmalar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="güncellenme"),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="ad")),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=100, verbose_name="soyad"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-posta"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="telefon"),
                ),
                (
                    "job_title",
                    models.CharField(blank=True, max_length=100, verbose_name="unvan"),
                ),
                (
                    "lifecycle_stage",
                    models.CharField(
                        choices=[
                            ("lead", "Aday"),
                            ("prospect", "Potansiyel"),
                            ("customer", "Müşteri"),
                            ("churned", "Kaybedilen"),
                        ],
                        default="lead",
                        max_length=20,
                        verbose_name="yaşam döngüsü",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Web sitesi"),
                            ("referral", "Referans"),
                            ("social", "Sosyal medya"),
                            ("event", "Etkinlik"),
                            ("ads", "Reklam"),
                            ("other", "Diğer"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="kaynak",
                    ),
                ),
                (
                    "preferred_channel",
                    models.CharField(
                        choices=[
                            ("email", "E-posta"),
                            ("phone", "Telefon"),
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                        ],
                        default="email",
                        max_length=20,
                        verbose_name="tercih edilen kanal",
                    ),
                ),
                (
                    "marketing_consent",
                    models.BooleanField(default=False, verbose_name="pazarlama izni"),
                ),
                (
                    "consent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="izin tarihi"
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False, verbose_name="skor"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notlar")),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="crm.company",
                        verbose_name="firma",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sorumlu",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="contacts",
                        to="crm.tag",
                        verbose_name="etiketler",
                    ),
                ),
            ],
            options={
                "verbose_name": "kişi",
                "verbose_name_plural": "kişiler",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="güncellenme"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="başlık")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="tutar",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="para birimi"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "Yeni"),
                            ("qualified", "Nitelikli"),
                            ("proposal", "Teklif"),
                            ("negotiation", "Pazarlık"),
                            ("won", "Kazanıldı"),
                            ("lost", "Kaybedildi"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="aşama",
                    ),
                ),
                (
                    "probability",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="olasılık (%)"
                    ),
                ),
                (
                    "expected_close",
                    models.DateField(
                        blank=True, null=True, verbose_name="beklenen kapanış"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="kapanış"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="sıra"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="crm.company",
                        verbose_name="firma",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="crm.contact",
                        verbose_name="kişi",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sorumlu",
                    ),
                ),
            ],
            options={
                "verbose_name": "fırsat",
                "verbose_name_plural": "fırsatlar",
                "ordering": ["stage", "position", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="güncellenme"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("note", "Not"),
                            ("call", "Arama"),
                            ("email", "E-posta"),
                            ("meeting", "Toplantı"),
                            ("task", "Görev"),
                        ],
                        default="note",
                        max_length=20,
                        verbose_name="tür",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="konu")),
                ("body", models.TextField(blank=True, verbose_name="açıklama")),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="son tarih"
                    ),
                ),
                ("done", models.BooleanField(default=False, verbose_name="tamamlandı")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sorumlu",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="crm.company",
                        verbose_name="firma",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="crm.contact",
                        verbose_name="kişi",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="crm.deal",
                        verbose_name="fırsat",
                    ),
                ),
            ],
            options={
                "verbose_name": "aktivite",
                "verbose_name_plural": "aktiviteler",
                "ordering": ["done", "due_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["stage", "position"], name="crm_deal_stage_df4b53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["email"], name="crm_contact_email_240305_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["lifecycle_stage"], name="crm_contact_lifecyc_90544e_idx"
            ),
        ),
    ]
